### ISSUE TITLE
Error Message Respective To The Field Separately

### ISSUE THREAD

**Issue by ateequrrahman97** [emretulek/jbvalidator#14]
How can we display messages against each input field and of my choice?
In messages, there is no support for this.

**Comment by ateequrrahman97** [comment]
It's working fine. I didn't understand at that time.

**Comment by ateequrrahman97** [comment]
??

**Comment by emretulek** [comment]
You can change the error message with the data-v-message property. This feature suppresses (replaces) all errors, there is no support for displaying different messages for each error.
