### ISSUE TITLE
How can we display Custom Error message

### ISSUE THREAD

**Issue by ateequrrahman97** [emretulek/jbvalidator#15]
//custom validate method
`validator.validator.custom = function(el, event){
   if($(el).is('[name=password]') && $(el).val().length < 5){
       return 'Your password is too weak.';
   }
}`
This method only return but it can not display any error on the screen.

**Comment by emretulek** [comment]
The returned string is used as error message, you can define rule and message for specific input.

**Comment by ateequrrahman97** [comment]
Okay, thanks @emretulek
