### ISSUE TITLE
Vertical alignment icons inside input

### ISSUE THREAD

**Issue by tolki5** [emretulek/jbvalidator#16]
I use Bootstrap 5 and jbvalidator (https://github.com/emretulek/jbvalidator).

I want to use icon inside input. Here is the code:

```
<div class="input-group mb-3"><i class="ci-user position-absolute top-50 translate-middle-y text-muted fs-base ms-3"></i>
    <input class="form-control rounded-start" type="text" placeholder="Username" required>
</div>
```
And here is result: https://i.stack.imgur.com/hRyUQ.jpg

if the validator marks it as incorrect, it moves the icon down because the vertical centering is set to 50%. Here is result: https://i.stack.imgur.com/IgC9q.jpg

I don't know how to elegantly center the icon vertically even if an error message is displayed.

**Comment by emretulek** [comment]
You can adjust with pixel instead of percentage value.  

html
```
<div class="input-group mb-3"><i class="form-icon ci-user position-absolute translate-middle-y text-muted fs-base ms-3"></i>
    <input class="form-control rounded-start" type="text" placeholder="Username" required>
</div>
```

css
`.form-icon {
    top:20px
}`

**Comment by tolki5** [comment]
> You can adjust with pixel instead of percentage value.
> 
> html
> 
> ```
> <div class="input-group mb-3"><i class="form-icon ci-user position-absolute translate-middle-y text-muted fs-base ms-3"></i>
>     <input class="form-control rounded-start" type="text" placeholder="Username" required>
> </div>
> ```
> 
> css
> `.form-icon { top:20px }`

It works! Thank you. Very simple solution:-) I used

`.form-icon { top:21px }`

Now it's perfectly in the middle!
