### ISSUE TITLE
Nice Library

### ISSUE THREAD

**Issue by carlblanchard** [emretulek/jbvalidator#17]
Thanks for creating a great library, I am having a little trouble with an edge case. 
I'm using the smart wizard library which breaks large forms into pages of a wizard 
https://github.com/techlab/jquery-smartwizard

The problem I am facing is that the validation doesn't kick in until the last page of the wizard when the form is submitted, or if I interact with the form elements. 

So my question to you is how would I manually invoke the validation routine?

Thanks in advance.

**Comment by emretulek** [comment]
It seems to work when interacting with form elements.
https://codepen.io/emretulek/pen/MWoEgpE

To control all inputs, you must submit the form, there is no external control method. (Actually it exists but cannot be used because its access is closed to the outside, I guess I should have changed it earlier.)

**Comment by emretulek** [comment]
I just added a new version, if you want to check for errors without submitting the form, you can use validator.checkAll() method.

**Comment by carlblanchard** [comment]
Yeah working like a treat 👍

**Comment by ateequrrahman97** [comment]
Hi @emretulek , I have used validator.checkAll() to validate but its return only counts of fields that are invalid and it validates the form instead of specific elements inside a specific div.
Can we add a mechanism to validate specific areas inside the form that are validated before going to the next step and prevent it?

**Comment by emretulek** [comment]
You can use the jQuery trigger() method to validate a particular form element.
E.g;
`$('input[name=username]').trigger('input')`
or you can group these inputs by giving them the same class.
`$('.group1').trigger('input') `

**Comment by ateequrrahman97** [comment]
> You can use the jQuery trigger() method to validate a particular form element. E.g; `$('input[name=username]').trigger('input')` or you can group these inputs by giving them the same class. `$('.group1').trigger('input') `

Hi @emretulek , 
I hope you are doing well.
I use this $('.group1').trigger('input'). but it cannot able to prevent to go to next step.
However, it shows the error but usually, wizards are prevented from true or false to go to the next step.
If we add the method that can return either true or false then it will be very easy to handle the wizard!?
We can pass the elements to the funtion to valdate it and it will return boolean?
`$("#smartwizard").on("leaveStep", function(e, anchorObject, currentStepIndex, nextStepIndex, stepDirection) {
            $('.step-'+(currentStepIndex+1)+'-inputs').trigger('input');
            $('.step-'+(currentStepIndex+1)+'-inputs').trigger('select');
            return false;
            // return confirm("Do you want to leave the step " + currentStepIndex + "?");
});`

**Comment by ateequrrahman97** [comment]
> > You can use the jQuery trigger() method to validate a particular form element. E.g; `$('input[name=username]').trigger('input')` or you can group these inputs by giving them the same class. `$('.group1').trigger('input') `
> 
> Hi @emretulek , I hope you are doing well. I use this $('.group1').trigger('input'). but it cannot able to prevent to go to next step. However, it shows the error but usually, wizards are prevented from true or false to go to the next step. If we add the method that can return either true or false then it will be very easy to handle the wizard!? We can pass the elements to the funtion to valdate it and it will return boolean? `$("#smartwizard").on("leaveStep", function(e, anchorObject, currentStepIndex, nextStepIndex, stepDirection) { $('.step-'+(currentStepIndex+1)+'-inputs').trigger('input'); $('.step-'+(currentStepIndex+1)+'-inputs').trigger('select'); return false; // return confirm("Do you want to leave the step " + currentStepIndex + "?"); });`

Thank you @emretulek for creating such an awesome validator.
I have added a function like you you have added checkAll() with a little bit modification.
Please have a look.
`        let checkSelected = function (event, div) {
            STATUS = 0;
            $(div).find(selector).each((i, el) => {
                validationRun(el, event);
            });
            return STATUS;
        }`
  I just pass the div to that function 
  `let count = validator.checkSelected(this, $('#step-'+(currentStepIndex+1)));`
  and it will return the count of invalid fields like checkAll() method.
  `            $("#smartwizard").on("leaveStep", function(e, anchorObject, currentStepIndex, nextStepIndex, stepDirection) {
                let count = validator.checkSelected(this, $('#step-'+(currentStepIndex+1)));
                console.log(count);
                if (count == 0) {
                    return true;
                }else {
                    return false;
                }
            });`
From that, it is working well.
But one thing if we return boolean from validationRun() function then we don't need a count of invalid fields.
If you look into it please reply here.
Thanks & Regards.
