### ISSUE TITLE
Not Working On Dynamically Added Elements

### ISSUE THREAD

**Issue by ateequrrahman97** [emretulek/jbvalidator#18]
Everything is good but If I am adding an element dynamically on the page, the pattern validation does not work, and also element is not available in the custom function.
Here is my code please review this.
`let li = '<li class="list-group-item p-0 border-bottom-0" id="tiktok-li">
                            <div class="input-group social-account-inputs position-relative border-bottom">
                                <a href="javascript:;" class="input-group-text bg-transparent border-0 p-0">
                                    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 32 32" width="24px" height="24px">
                                        <g id="surface74321354">
                                        <path style=" stroke:none;fill-rule:nonzero;fill:rgb(80.000001%,80.000001%,80.000001%);fill-opacity:1;" d="M 4.769531 30.398438 C 3.019531 30.398438 1.601562 28.980469 1.601562 27.230469 L 1.601562 4.769531 C 1.601562 3.019531 3.019531 1.601562 4.769531 1.601562 L 27.230469 1.601562 C 28.980469 1.601562 30.398438 3.019531 30.398438 4.769531 L 30.398438 27.230469 C 30.398438 28.980469 28.980469 30.398438 27.230469 30.398438 Z M 26.59375 29.761719 C 28.339844 29.761719 29.761719 28.339844 29.761719 26.59375 L 29.761719 5.40625 C 29.761719 3.660156 28.339844 2.238281 26.59375 2.238281 L 5.40625 2.238281 C 3.660156 2.238281 2.238281 3.660156 2.238281 5.40625 L 2.238281 26.59375 C 2.238281 28.339844 3.660156 29.761719 5.40625 29.761719 Z M 26.59375 29.761719 "/>
                                        <path style=" stroke:none;fill-rule:nonzero;fill:rgb(0%,0%,0%);fill-opacity:1;" d="M 7.054688 0.601562 C 3.507812 0.601562 0.601562 3.507812 0.601562 7.054688 L 0.601562 24.945312 C 0.601562 28.492188 3.507812 31.398438 7.054688 31.398438 L 24.945312 31.398438 C 28.492188 31.398438 31.398438 28.492188 31.398438 24.945312 L 31.398438 7.054688 C 31.398438 3.507812 28.492188 0.601562 24.945312 0.601562 Z M 7.054688 3.398438 L 24.945312 3.398438 C 26.980469 3.398438 28.601562 5.019531 28.601562 7.054688 L 28.601562 24.945312 C 28.601562 26.980469 26.980469 28.601562 24.945312 28.601562 L 7.054688 28.601562 C 5.019531 28.601562 3.398438 26.980469 3.398438 24.945312 L 3.398438 7.054688 C 3.398438 5.019531 5.019531 3.398438 7.054688 3.398438 Z M 17.398438 6.199219 L 17.398438 20.199219 C 17.398438 21.761719 16.164062 23 14.601562 23 C 13.035156 23 11.800781 21.761719 11.800781 20.199219 C 11.800781 18.636719 13.035156 17.398438 14.601562 17.398438 L 14.601562 14.601562 C 11.523438 14.601562 9 17.125 9 20.199219 C 9 23.277344 11.523438 25.800781 14.601562 25.800781 C 17.675781 25.800781 20.199219 23.277344 20.199219 20.199219 L 20.199219 11.644531 C 21.359375 12.542969 22.734375 13.179688 24.296875 13.199219 L 24.339844 10.398438 C 22.035156 10.367188 20.199219 8.515625 20.199219 6.199219 Z M 17.398438 6.199219 "/>
                                        </g>
                                    </svg>
                                </a>
                                <input type="hidden" name="social_accounts[followers][]" value="" />
                                <input type="text" class="form-control common-social-input border-0 pe-2rem" pattern="^\S+$" data-pattern-message="i.e. johndoe"
                                name="social_accounts[url][]" placeholder="username" id="tiktok" value="" required />
                                <input type="hidden" name="social_accounts[provider][]" value="tiktok">
                                <a href="javascript:;" class="position-absolute bg-transparent hide-show-icon-position remove-field"
                                    data-option-id="tiktok-li" style="z-index: 99;" ><i class='bx bx-x'></i></a>
                            </div>
                        </li>';
$(li).insertAfter('#select-li');`

I use tick backs for li but it does not work on github so I change it to single qoutes.
`               validator.validator.custom = function(el, event) {
                    if ($(el).is('[name="social_accounts[url][]"]')) {
                        console.log($(el));
                    }
                }`
this element does not appear in the console ever however if I add this element on page load it gets perfectly.
@emretulek @Mibou @bredecl please look into it

**Comment by emretulek** [comment]
Call the validator.reload() method every time you add a new element.

`validator.validator.custom = function(el, event) { if ($(el).is('[name="social_accounts[url][]"]')) { console.log($(el)); } }`

The input must be valid to give a custom error message. If the pattern is incorrect, you will not be able to see it in the console, if the pattern is valid, you will be able to see it in the console so that you can give a different error message.

**Comment by ateequrrahman97** [comment]
> validator.reload()

validator.reload is not a function

@emretulek

**Comment by emretulek** [comment]
The cdn files can take up to 24 hours to update, you can try using version 1.0.5 directly if you want. 

https://www.jsdelivr.com/package/npm/@emretulek/jbvalidator?version=1.0.5

**Comment by ateequrrahman97** [comment]
Thank you, It's working fine!
